### ISSUE TITLE
Explanation ends mid-sentence

### ISSUE THREAD

**Issue by johnsaigle** [0xPARC/zk-bug-tracker#3]
Hi, thanks for making this resource!

I noticed one of the explanations ends in the middle of the sentence at the word 'prevent'

https://github.com/0xPARC/zk-bug-tracker/blob/8ad138668270e0aa8dac3a3f8f5d3589d5e1281f/README.md?plain=1#L144-L146

**Comment by kcharbo3** [comment]
Thanks for this! Just updated it.
